#Microservices Service Registry
#A service registry is a database used to keep track of the available instances of each microservice
# in an application. The service registry needs to be updated each time a new service comes online and
# whenever a service is taken offline or becomes unavailable.
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # Below are false because this is server not client
    register-with-eureka: false
    fetch-registry: false


